name: Executar lembrete diário

on:
  schedule:
    - cron: '12 12 * * *'
  workflow_dispatch:

jobs:
  lembrete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: pip install -r requirements.txt
      - name: Executar lembrete
        run: python executar_lembrete.py
